#%RAML 1.0
title: exp-salesforce-accounts-api
baseUri: http://localhost:8081/api/*

traits:
  client-id-requred : !include traits/client-id-required.raml
  common-errors : !include traits/common-errors.raml

types:
  post-deposit-type : !include types/post-deposit-details-req-type.raml


/getDeposits :  
    post:
      is : [client-id-requred, common-errors]
      body:
        application/json:
          example: !include examples/post-deposit-details-req.json
          type : post-deposit-type
            
      responses:
        200:
          body:
            application/json:
              example: !include examples/post-deposit-details-res.json
                
        
        
            
        